spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fq_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Quyuhan0415
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  alioss:
    bucket-name: fq-blog-oss
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id:
    access-key-secret: